### ISSUE TITLE
Unreachable code

### ISSUE THREAD

**Issue by jnyrup** [jakobbotsch/Fuzzlyn#1]
Unsure whether this a bug or not, so reporting it.

https://github.com/jakobbotsch/Fuzzlyn/blob/b1391faf9f533d1613c46118d17b7bc2b1af2c3f/Fuzzlyn/Methods/FuncGenerator.cs#L439-L443

**Comment by jakobbotsch** [comment]
It currently serves as a reminder for me to implement casts. The current implementation does not work properly. One way to fix it is to pick a random type that can actually be cast to the target type, or bail if there are no such types (for ref types or aggregate types).

The reason I have not implemented it like that is that such an implementation is not really ideal. The main issue is that the expression generator can only generate expressions of a single type. However, if we want to generate a cast to an integer type, we don't really care which integer type the source expression has.
I have experimented with allowing the expression generator to accept several types to generate, but complexity wise (in terms of the code) it was much worse. Any way, Fuzzlyn already inserts casts in a bunch of situations, so casts have reasonable coverage already. See for example
https://github.com/jakobbotsch/Fuzzlyn/blob/b1391faf9f533d1613c46118d17b7bc2b1af2c3f/Fuzzlyn/Methods/FuncGenerator.cs#L681-L682
https://github.com/jakobbotsch/Fuzzlyn/blob/b1391faf9f533d1613c46118d17b7bc2b1af2c3f/Fuzzlyn/Methods/FuncGenerator.cs#L768-L771

**Comment by jnyrup** [comment]
Thanks for the detailed explanation.
