### ISSUE TITLE
seed output expects mismatching output - cannot manually replicate

### ISSUE THREAD

**Issue by bradmarder** [jakobbotsch/Fuzzlyn#10]
I'm a bit confused which version of dotnet Fuzzlyn is comparing outputs against. I was able to generated a seed with expected mismatched outputs, but they **do match** when I run the program manually against multiple versions of .net 5-7.  Maybe I am missing some compiler option, or not using a certain version of dotnet?

Also, if I compile Fuzzlyn with .net 7, it still gives mismatched outputs for this seed, but with a different value for release.

```c#
// Generated by Fuzzlyn v1.5 on 2022-03-15 01:15:21
// Run on X64 Windows
// Seed: 5300781440690032129
// Reduced from 111.4 KiB to 1.4 KiB in 00:00:39
// Debug: Outputs 0
// Release: Outputs 396
public struct S0
{
    public ushort F0;
    public long F2;
}

public class Program
{
    public static IRuntime s_rt;
    public static int s_1;
    public static void Main()
    {
        CollectibleALC alc = new CollectibleALC();
        System.Reflection.Assembly asm = alc.LoadFromAssemblyPath(System.Reflection.Assembly.GetExecutingAssembly().Location);
        System.Reflection.MethodInfo mi = asm.GetType(typeof(Program).FullName).GetMethod(nameof(MainInner));
        System.Type runtimeTy = asm.GetType(typeof(Runtime).FullName);
        mi.Invoke(null, new object[] { System.Activator.CreateInstance(runtimeTy) });
    }

    public static void MainInner(IRuntime rt)
    {
        s_rt = rt;
        S0 vr5 = new S0();
        bool vr4 = M26(vr5);
    }

    public static bool M26(S0 arg2)
    {
        var vr1 = (short)((-arg2.F0) * -1);
        M29(vr1);
        bool vr0 = s_1 == M28();
        return true;
    }

    public static short M28()
    {
        return default(short);
    }

    public static void M29(short arg1)
    {
        s_rt.WriteLine("c_85", arg1);
    }
}

public interface IRuntime
{
    void WriteLine<T>(string site, T value);
}

public class Runtime : IRuntime
{
    public void WriteLine<T>(string site, T value) => System.Console.WriteLine(value);
}

public class CollectibleALC : System.Runtime.Loader.AssemblyLoadContext
{
    public CollectibleALC() : base(true)
    {
    }
}
```

**Comment by jakobbotsch** [comment]
> I'm a bit confused which version of dotnet Fuzzlyn is comparing outputs against. I was able to generated a seed with expected mismatched outputs, but they do match when I run the program manually against multiple versions of .net 5-7. Maybe I am missing some compiler option, or not using a certain version of dotnet?

Fuzzlyn runs the programs with the host passed to `--host`.
To reproduce your problem tiered compilation has to be turned off, otherwise even the release build is not optimize. You can turn it off with `DOTNET_TieredCompilation=0` environment variable or [see here](https://docs.microsoft.com/en-us/dotnet/core/runtime-config/compilation) for more details.

This particular problem is the same as https://github.com/dotnet/runtime/issues/61074.

**Comment by jakobbotsch** [comment]
Added a note to the readme in ec06d9c4ee6645fa793a79a626cafabee1b8e2c0 about tiered compilation.
