### ISSUE TITLE
Expression is always true

### ISSUE THREAD

**Issue by jnyrup** [jakobbotsch/Fuzzlyn#2]
As far as [Roslynator](https://github.com/JosefPihrt/Roslynator/blob/master/docs/analyzers/RCS1215.md) and I can tell this expression `ogDebugCompile.CompileErrors.Length >= 0` always evaluates to true.

https://github.com/jakobbotsch/Fuzzlyn/blob/b1391faf9f533d1613c46118d17b7bc2b1af2c3f/Fuzzlyn/Reduction/Reducer.cs#L399-L402

**Comment by jakobbotsch** [comment]
Yep, that's a bug. It should be `ogDebugCompile.CompileErrors.Length > 0`. Nice find!
