### ISSUE TITLE
Fuzzlyn should no longer pass its own executable name as the first arg when starting child processes

### ISSUE THREAD

**Issue by aevitas** [jakobbotsch/Fuzzlyn#5]
Since the release of .NET Core 3.0, apps can be run using their executable names rather than `dotnet appname`.

Currently, in `RunSeparately`, `fuzzlyn` is passed as the first arg, and is interpreted as an arg for the `dotnet` process:

```csharp
ProcessStartInfo info = new ProcessStartInfo
{
    FileName = dotnet,
    Arguments = "fuzzlyn --execute-programs",
    WorkingDirectory = fuzzlynDir,
    RedirectStandardOutput = true,
    RedirectStandardInput = true,
    UseShellExecute = false,
};
```

However, because Fuzzlyn is now its own executable, this arg is no longer needed and causes a `JsonReaderException` because the arg is passed to the `JsonConvert.DeserializeObject` further down the method.

This can be fixed by removing fuzzlyn from the arguments.

**Comment by jakobbotsch** [comment]
Fixed by #6
